# Generated by Django 5.0.6 on 2024-06-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='content_loaded',
            new_name='load_file_content',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('txt', 'Tabulated text'), ('csv', 'Comma-separated values'), ('tsv', 'Tab-separated values'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cb.project'),
        ),
        migrations.AlterField(
            model_name='comparisonmatrix',
            name='matrix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampleannotation',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
