# Generated by Django 5.0.6 on 2024-06-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0002_rename_content_loaded_projectfile_load_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
