# Generated by Django 5.0.6 on 2024-06-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0005_searchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_term', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='user',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='analysis_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='cb.analysisgroup'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='cb.searchsession'),
        ),
    ]
