# Generated by Django 5.0.6 on 2024-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0006_searchsession_remove_searchresult_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='analysis_groups',
            field=models.ManyToManyField(blank=True, related_name='search_sessions', to='cb.analysisgroup'),
        ),
    ]
