# Generated by Django 5.0.6 on 2024-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0009_searchresult_file_searchresult_headline_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='phosphorylation',
            field=models.BooleanField(default=False),
        ),
    ]
