# Generated by Django 5.0.6 on 2024-06-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0010_analysisgroup_phosphorylation'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
