# Generated by Django 5.0.6 on 2024-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0011_searchsession_completed_searchsession_in_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='found_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
