# Generated by Django 5.0.6 on 2024-06-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0012_searchsession_found_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisgroup',
            old_name='phosphorylation',
            new_name='ptm',
        ),
    ]
