# Generated by Django 5.0.6 on 2024-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0013_rename_phosphorylation_analysisgroup_ptm'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
