# Generated by Django 5.0.6 on 2024-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0014_projectfile_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='log10_p_value',
            field=models.FloatField(default=1.31),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='log2_fc',
            field=models.FloatField(default=0.6),
        ),
    ]
