# Generated by Django 5.0.6 on 2024-06-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0016_rename_headline_results_searchresult_searched_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='foldChange',
            new_name='log10_p',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='pValue',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='log2_fc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
