# Generated by Django 5.0.6 on 2024-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0018_searchsession_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='curtain_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
