# Generated by Django 5.0.6 on 2024-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0019_analysisgroup_curtain_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('taxon', models.IntegerField()),
                ('official_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['official_name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='organism',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
