# Generated by Django 5.0.6 on 2024-06-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0020_species_project_organism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organism',
        ),
        migrations.AddField(
            model_name='project',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cb.species'),
        ),
    ]
