# Generated by Django 5.0.6 on 2024-06-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0021_remove_project_organism_project_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='synonyms',
            new_name='synonym',
        ),
    ]
