# Generated by Django 5.0.6 on 2024-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0022_rename_synonyms_species_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='copy_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file_category',
            field=models.CharField(choices=[('searched', 'MS Search Output'), ('df', 'Differential Analysis'), ('copy_number', 'Copy Number'), ('raw', 'Raw Data'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
