# Generated by Django 5.0.6 on 2024-06-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0025_alter_analysisgroup_analysis_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255)),
                ('link_id', models.CharField(max_length=255)),
                ('data', models.TextField(blank=True, null=True)),
                ('settings', models.TextField(blank=True, null=True)),
                ('annotations', models.TextField(blank=True, null=True)),
                ('analysis_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtain_data', to='cb.analysisgroup')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
