# Generated by Django 5.0.6 on 2024-06-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0026_curtaindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtaindata',
            name='selectionMap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curtaindata',
            name='selections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
