# Generated by Django 5.0.6 on 2024-06-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0027_curtaindata_selectionmap_curtaindata_selections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curtaindata',
            old_name='selectionMap',
            new_name='selection_map',
        ),
    ]
