# Generated by Django 5.0.6 on 2024-06-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0028_rename_selectionmap_curtaindata_selection_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_sessions', to='cb.species'),
        ),
    ]
