# Generated by Django 5.0.6 on 2024-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0029_searchsession_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('greeting', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='collates', to='cb.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
