# Generated by Django 5.0.6 on 2024-09-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0030_collate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collates', models.ManyToManyField(blank=True, related_name='tags', to='cb.collate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
