# Generated by Django 5.0.6 on 2024-09-20 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0032_labgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collate',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='collates', to=settings.AUTH_USER_MODEL),
        ),
    ]
