# Generated by Django 5.0.6 on 2024-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0034_searchresult_ptm_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcellularLocation',
            fields=[
                ('location_identifier', models.TextField(blank=True, null=True)),
                ('topology_identifier', models.TextField(blank=True, null=True)),
                ('orientation_identifier', models.TextField(blank=True, null=True)),
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_a', models.TextField(blank=True, null=True)),
                ('part_of', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('gene_ontology', models.TextField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
    ]
