# Generated by Django 5.0.6 on 2024-11-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0036_sourcefile_metadatacolumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadatacolumn',
            options={'ordering': ['column_position']},
        ),
        migrations.RenameField(
            model_name='metadatacolumn',
            old_name='position',
            new_name='column_position',
        ),
    ]
