# Generated by Django 5.0.6 on 2024-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0037_alter_metadatacolumn_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanDisease',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('accession', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cross_references', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('cross_references', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
