# Generated by Django 5.0.6 on 2024-11-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0038_humandisease_tissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSUniqueVocabularies',
            fields=[
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('term_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
        migrations.CreateModel(
            name='Unimod',
            fields=[
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
    ]
