# Generated by Django 5.1.5 on 2025-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0043_searchsession_data_type_alter_searchresult_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collate',
            name='data_type',
            field=models.CharField(blank=True, choices=[('proteomics', 'Proteomics'), ('ptm', 'Post-translational Modification'), ('proteogenomics', 'Proteogenomics'), ('metabolomics', 'Metabolomics'), ('lipidomics', 'Lipidomics'), ('glycomics', 'Glycomics'), ('glycoproteomics', 'Glycoproteomics')], default='proteomics', max_length=255, null=True),
        ),
    ]
