# Generated by Django 5.1.5 on 2025-04-29 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0045_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collate',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collate',
            name='share_with',
            field=models.ManyToManyField(blank=True, related_name='shared_collates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='share_with',
            field=models.ManyToManyField(blank=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
